#!/bin/bash
# Parts of this script is taken from the tutorial:
# http://bookofzeus.com/harden-ubuntu
# In a best effort manner

# Variables used in this script
OPENSSL_VERSION=openssl-1.0.2g
SHA256SUM=sha256
PGPSUM=pgp.asc

# Clean up everything
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get autoremove -y
sudo apt-get autoclean -y

# install unattended upgrades

sudo apt-get install unattended-upgrades

# Creates the file /etc/apt/apt.conf.d/20auto-upgrades
sudo dpkg-reconfigure -plow unattended-upgrades

# Customize automatic updates

UPGRADE_SETUP="// Automatically upgrade packages from these (origin:archive) pairs \n
  Unattended-Upgrade::Allowed-Origins {\n
      \"\${distro_id}:\${distro_codename}-security\";\n
  //  \"\${distro_id}:\${distro_codename}-updates\";\n
  //  \"\${distro_id}:\${distro_codename}-proposed\";\n
  //  \"\${distro_id}:\${distro_codename}-backports\";\n
  };\n
  \n
  //Unattended-Upgrade::Mail \"my_user@my_domain.com\";"
  
sudo echo -e $UPGRADE_SETUP > /etc/apt/apt.conf.d/20auto-upgrades

# Install some necessary packages
sudo apt-get install build-essential

# Create hard to get user
# You  would of course modify this to your own preferences
sudo useradd -d /home/hard-to-get-user-143 -s /bin/bash -m hard-to-get-user-143

# Give sudo access to the user
sudo usermod -a -G sudo hard-to-get-user-g

# Set a password
sudo passwd hard-to-get-user-143

# Lock the root account
sudo passwd -l root

# Disable ipv6
# If you need to remove ipv6 settings, uncomment this line
# grep -v "ipv6" /etc/sysctl.conf > temp && mv temp /etc/sysctl.conf
DISABLE_IPV6="#disable ipv6\nnet.ipv6.conf.all.disable_ipv6 = 1\nnet.ipv6.conf.default.disable_ipv6 = 1\nnet.ipv6.conf.lo.disable_ipv6 = 1\n"

sudo echo -e $DISABLE_IPV6 >> /etc/sysctl.conf
sudo sysctl -p

# Disable IRQ Balance, so that hardware interrupts don't show up in your threads
sudo find /etc/default/irqbalance -type f -exec sed -i 's/ENABLED="1"/ENABLED="0"/g' {} \;

# Upgrade openssl package, so that it is patched against heartbleed bug
sudo apt-get upgrade openssl libssl-dev
sudo apt-cache policy openssl libssl-dev

# Install and switch to latest stable openssl library
curl https://www.openssl.org/source/$OPENSSL_VERSION.tar.gz > $OPENSSL_VERSION.tar.gz
curl https://www.openssl.org/source/$OPENSSL_VERSION.tar.gz.$SHA256SUM > $SHA256SUM
curl https://www.openssl.org/source/$OPENSSL_VERSION.tar.gz.asc > $PGPSUM

# Make the file a proper sha256 file to enable autochecking
(echo " $OPENSSL_VERSION.tar.gz " & cat ${SHA256SUM}) | xargs -n 2 | awk '{printf $1 " " $2}' > tmp
mv tmp $SHA256SUM

# Make sure everything is written to disk on slow vms ..
sleep .2

# Check the sha256sum, if not OK, ABORT with error code 1
FILE_OK=$(sha256sum -c ${SHA256SUM})

if echo $FILE_OK | grep -q 'OK';then
  echo "The Sha256Sum matched the downloaded source bundle"
else
  echo "The Sha256sum of downloaded file does not match"
  exit 1
fi

echo "Extracting and installing files .."
tar vxzf $OPENSSL_VERSION.tar.gz
echo "Entering archive"

cd $OPENSSL_VERSION
echo "configuring the packages"

sudo ./config

echo "building"
sudo make

echo "installing"
sudo make install

echo "Switch to newly installed openssl"
sudo ln -sf /usr/local/ssl/bin/openssl `which openssl`

cd ../

# Clean up openssl installation
rm -rf $OPENSSL_VERSION
rm $OPENSSL_VERSION.tar.gz
rm $SHA256SUM
rm $PGPSUM

# Secure Shared Memory
#secure shared memory
SEC_SHARED_MEM="tmpfs     /run/shm    tmpfs	defaults,noexec,nosuid	0	    0"
sudo echo >> $SECH_SHARED_MEM
sudo echo -e $SEC_SHARED_MEM >> /etc/fstab


